# Generated by Django 5.2.1 on 2025-05-08 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Le nom doit contenir au moins 3 caractères', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='nom')),
                ('telephone', models.CharField(help_text='Format: 8 chiffres commençant par 2, 3 ou 4', max_length=8, validators=[django.core.validators.RegexValidator(message='Entrez un numéro de téléphone mauritanien valide', regex='^[234]\\d{7}$')], verbose_name='téléphone')),
                ('date_naissance', models.DateField(help_text='Format requis: aaaa-mm-jj (exemple: 1990-05-15)', verbose_name='date de naissance')),
            ],
        ),
    ]
